id: DBFF9C09A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:24:06+00:00'
last_modified: '2022-05-26T10:06:10.586375+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    2f3a:
      image_group_id: I1PD95863
      title: རྣལ་འབྱོར་ཆེན་པོའི་རྒྱུད་དཔལ་གསང་བ་འདུས་པའི་བསྐྱེད་པའི་རིམ་པ་བསྒོམ་པའི་ཐབས་མདོ་དང་བསྲེས་པ།
      total_pages: 1634
      order: 18
      base_file: 2f3a.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
